import math
# Device specifications
## Known display stats
SCREEN_XSIZE_PIX = 1920
SCREEN_YSIZE_PIX = 1080
SCREEN_DIAGONAL_INCH = 15.6

## Calculated display stats
SCREEN_RATIO = SCREEN_XSIZE_PIX / SCREEN_YSIZE_PIX
SCREEN_YSIZE_INCH = math.sqrt((SCREEN_DIAGONAL_INCH ** 2) / (SCREEN_RATIO ** 2 + 1))
SCREEN_XSIZE_INCH = SCREEN_RATIO * SCREEN_YSIZE_INCH
# pixels per inch
SCREEN_PPI = SCREEN_XSIZE_PIX / SCREEN_XSIZE_INCH

# Plot specifications
""" Dots per inch """
FIG_DPI = SCREEN_PPI
FIG_XSIZE_INCH = SCREEN_XSIZE_INCH * 0.9
FIG_YSIZE_INCH = SCREEN_YSIZE_INCH